version: '3.8'

services:
  spring-boot-app:
    image: jvanderlith085/carorderingproject:latest
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql-db:3306/car_ordering
      - DB_USER=co_user
      - DB_PASSWORD=p@55w0rd

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: p@55w0rd
      MYSQL_DATABASE: car_ordering  # Corrected indentation
      MYSQL_USER: co_user
      MYSQL_PASSWORD: p@55w0rd
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: